apiVersion: v1
kind: Secret
metadata:
  name: bbhealthapp-secret
  namespace: bbhealthapp
type: Opaque
stringData:
  DB_HOST: "bbhealthapp-dev-db.cva4a8guy8id.us-west-2.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "bbhealthapp"
  DB_USERNAME: "admin"
  DB_PASSWORD: "ChangeMe123"
  JWT_SECRET: "bbhealthapp-secret-key"