spring.profiles.active=dev

# =========================
# SERVER (INSIDE CONTAINER)
# =========================
server.port=8080

# =========================
# SECURITY
# =========================
token.secret=10d73c0906053a33e5b96500d7c5eeaf717f199a54c5baff4d7da9d0b0

server.error.include-message=always

app.testrun=false

spring.jackson.serialization.fail-on-empty-beans=false

# =========================
# MULTIPART CONFIG
# =========================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

# =========================
# FILE STORAGE
# =========================
file.upload-dir=useruploads