spring.profiles.active=dev

# =========================
# SERVER PORT (INSIDE CONTAINER)
# =========================
server.port=8081

# =========================
# SECURITY / TOKEN
# =========================
token.secret=10d73c0906053a33e5b96500d7c5eeaf1674ed717f199a54c5baff4d7da9d0b0

server.error.include-message=always

app.testrun=false

spring.jackson.serialization.fail-on-empty-beans=false

# =========================
# MULTIPART CONFIG
# =========================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

# =========================
# FILE STORAGE
# =========================
file.upload-dir=useruploads

# =========================
# MASTER SERVICE (DOCKER NETWORK)
# =========================
MASTER_SVC_HOST=master-service
MASTER_SVC_PORT=8080

rootURL=http://${MASTER_SVC_HOST}:${MASTER_SVC_PORT}